### ISSUE TITLE
Roadmap: Better spec helpers

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1005]
- ActionHero Version: all
- Node.js Version: all
- Operating System: all

When you generate a task or action, a test for that new file should also be generated, and you should be able to run that test with no additional setup

---

- [x] Generating an action should generate a related test
- [x] we can test that a task was enqueued (normal queue)
- [x] we can test that a task was enqueued (future queue)

**Comment by evantahler** [comment]
This will require us to make some choices about test runners (mocha) and assertion tools (chai), and also how to book the server in test mode.  This "booting" process should be part of core.

**Comment by evantahler** [comment]
Task enqueuing test helpers added via https://github.com/actionhero/actionhero/pull/1331

**Comment by gcoonrod** [comment]
Anything else @evantahler?

**Comment by evantahler** [comment]
I think that's it!
